# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5401dfc2e04065930d743332ced842896062ee938b49c8dd4a06aefb83676637d8105794b67e6ece46024f95148ed493cee91cdf9b3359412d49c7b7483f9a30

test:
  secret_key_base: ee6745eeb11016ce0ef5953558c68cc866943db9e1c9b33c92bc3acd3dfb53431c76a1959458c930ebdf385f54a95f1ce23ce041ee89d5346ed9fd9c2d8e80b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
